database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "admin"
  name: "dronedelivery"
  ssl_mode: "disable"

kafka:
  host: "localhost"
  port: 9092
  missions_created_topic: "missions.created"
  missions_lifecycle_topic: "missions.lifecycle"
  drone_telemetry_topic: "drone.telemetry"

redis:
  host: "localhost"
  port: 6379

mission_service:
  host: "localhost"
  port: 8080
  