services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
    - drone-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dronedelivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dronedelivery"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
    - drone-net

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    user: root
    environment:
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw  # Фиксированный кластер ID
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT_HOST://:9092,PLAINTEXT_DOCKER://:9094,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LOG_DIRS=/kafka/kraft-combined-logs
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/kafka/kraft-combined-logs
    networks:
      - drone-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9094  # Используем внутренний порт
      - KAFKA_CLUSTERS_0_NAME=kraft
      - KAFKA_UI_AUTH_ENABLED=false
    networks:
      - drone-net

  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["bash", "-lc"]
    command:
      - |
        set -e
        echo "Waiting for Kafka..."
        for i in {1..60}; do
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --list >/dev/null 2>&1 && break
          sleep 2
        done
        echo "Creating topics (if not exist)..."
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic missions.created --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic missions.lifecycle --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic drone.telemetry --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic drone.lifecycle --partitions 1 --replication-factor 1
        echo "Kafka topics ready."
    restart: "no"
    networks:
      - drone-net

  mission-service:
    build:
      context: .
      dockerfile: Dockerfile.mission
    container_name: mission-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      kafka:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - configPath=config.docker.yaml
    networks:
      - drone-net

  drone-service:
    build:
      context: .
      dockerfile: Dockerfile.drone
    container_name: drone-service
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    environment:
      - configPath=config.docker.yaml
    networks:
      - drone-net

  telemetry-extractor:
    build:
      context: .
      dockerfile: Dockerfile.telemetry
    container_name: telemetry-extractor
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      kafka:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - configPath=config.docker.yaml
    networks:
      - drone-net

volumes:
  redis_data:
  postgres_data:
  kafka_data:

networks:
  drone-net:
    name: drone-net
    driver: bridge
